name: env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas
  - scikit-learn
  - pyarrow
  - joblib
  - lightgbm
  - catboost
  - optuna
  - imbalanced-learn
  - xgboost
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel>=6.29
  - ipython>=8.18
  - tqdm>=4.66
  - llvmlite  # Install via conda to avoid distutils issue
  - numba     # Usually depends on llvmlite
  - pip:
      - numpy==1.23.5
      - scipy==1.11.4
      - tensorflow==2.12.0
      - shap>=0.45
      - raiwidgets==0.31.0
      - responsibleai==0.31.0